version: '3'

services:
  react-app:
    container_name: react-app
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    logging:
      driver: none
    env_file: ../.env
  api-server:
    container_name: api-server
    build: ./backend
    ports:
      - "4000:4000"
    links:
      - mongo
    env_file: ../.env
  mongo:
    image: mongo
    restart: always
    volumes:
      - ../mongo_data:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: none
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - certs:/etc/nginx/certs:ro
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    env_file: ../.env
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
  nginx:
    build: ./nginx
    expose:
      - "80"
    links:
      - api-server
      - react-app
      - nginx-proxy
      - letsencrypt
    env_file: ../.env
    restart: always
volumes:
  certs:
  html:
  vhostd:
