version: '3'

services:
  react-app:
    container_name: react-app
    build: ./frontend
    stdin_open: true
    ports:
      - "3000:3000"
    logging:
      driver: none
    environment:
      - REACT_APP_PASSWORD=4321
      - REACT_APP_ADMIN_PASSWORD=9876
      - REACT_APP_API_URL=/api
  api-server:
    container_name: api-server
    build: ./backend
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo/cryptopagosdb
      - PORT=4000
      - PASSWORD=4321
      - ADMINPASSWORD=9876
      - NODE_ENV=production
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - certs:/etc/nginx/certs:ro
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
    labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
  nginx:
    build: ./nginx
    expose:
      - "80"
    links:
      - api-server
      - react-app
      - nginx-proxy
      - letsencrypt
    environment: 
      - VIRTUAL_HOST=decoinpay.com,www.decoinpay.com
      - LETSENCRYPT_HOST=decoinpay.com,www.decoinpay.com
    restart: always
volumes:
  certs:
  html:
  vhostd: