# This is a basic workflow to help you get started with Actions

name: DIGITALOCEAN_DEPLOY
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@main

      - name: Stop docker-compose
        run: docker-compose stop
        
      - name: Bild docker-compose
        run: docker-compose build
        
      - name: Start docker-compose
        run: docker-compose up -d
